title: MARIO BERTONCINI
subtitle: OPERE PER PIANOFORTE
email: jacopo.petrucci.phd@consaq.it
description: "Catalogo digitale delle opere pianistiche con fonti archivistiche dall'Akademie der Künste di Berlino"
author: "Jacopo Petrucci"
baseurl: "/catalogo-bertoncini"
url: "https://jacopopetrucci.github.io"

theme: minima

plugins:
  - jekyll-feed

collections:
  opere:
    output: true
    permalink: /opere/:name/
