title: MARIO BERTONCINI
subtitle: OPERE PER PIANOFORTE
email: jacopo.petrucci.phd@consaq.it
description: "Catalogo digitale delle opere pianistiche"
author: "Jacopo Petrucci"
baseurl: "/catalogo-bertoncini"
url: "https://jacopopetrucci.github.io"

theme: minima

plugins:
  - jekyll-feed

collections:
  opere:
    output: true
    permalink: /opere/:name/

header_pages: []

defaults:
  - scope:
      path: ""
      type: opere
    values:
      layout: opera
      is_opera: true